// <auto-generated />
using System;
using IMIP.Tochu.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMIP.Tochu.Infrastructure.Migrations
{
    [DbContext(typeof(TochuDBContext))]
    partial class TochuDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMIP.Tochu.Domain.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.Entities.SI_CODEMST", b =>
                {
                    b.Property<string>("KBN")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("ENUM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("EYOBI")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("NM")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("KBN", "ID");

                    b.ToTable("SI_CODEMST", "dbo");
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.Entities.SI_SEINOUMST", b =>
                {
                    b.Property<string>("PRODUCT")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NOUSCD")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("NUM")
                        .HasColumnType("int");

                    b.Property<decimal?>("MAX")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MIN")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PRODUCT", "NOUSCD", "NUM");

                    b.ToTable("SI_SEINOUMST", "dbo");
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.entities.SI_MEMO", b =>
                {
                    b.Property<string>("JIGYOUSHO")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)");

                    b.Property<int>("NUM")
                        .HasColumnType("int");

                    b.Property<string>("MEMO")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("JIGYOUSHO", "NUM");

                    b.ToTable("SI_MEMO", "dbo");
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.entities.SI_SEINOUDATA", b =>
                {
                    b.Property<int>("JUCHUUNO")
                        .HasColumnType("int");

                    b.Property<int>("NUM")
                        .HasColumnType("int");

                    b.Property<string>("COMM")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("JUCHUSUU")
                        .HasColumnType("int");

                    b.Property<string>("LOTNO")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("MA150")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MA20")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MA30")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NISUGATACD")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime?>("NOUKI")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOUSCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("NOUSSNM")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("PRINTDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("SUUJP")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<decimal?>("T10")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T100")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T110")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T120")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T130")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T140")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T150")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T160")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T20")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T30")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T40")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T50")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T60")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T70")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T80")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("T90")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TANTOU1")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TANTOU2")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TANTOU3")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("UPTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("USERHINBAN")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("JUCHUUNO", "NUM");

                    b.ToTable("SI_SEINOUDATA", "dbo");
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.entities.SI_TANTOU", b =>
                {
                    b.Property<string>("JIGYOUSHO")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)");

                    b.Property<int>("NUM")
                        .HasColumnType("int");

                    b.Property<string>("TEXT1")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("JIGYOUSHO", "NUM");

                    b.ToTable("SI_TANTOU", "dbo");
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.entities.T0000MS_Item_RCS", b =>
                {
                    b.Property<string>("UserHinban")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("UserHinban");

                    b.Property<string>("UserHinmei")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("UserHinmei");

                    b.HasKey("UserHinban");

                    b.ToTable("T0000MS_Item_RCS", (string)null);
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.entities.T0000RR_Juchuu_RCS", b =>
                {
                    b.Property<int>("JuchuuNO")
                        .HasColumnType("int");

                    b.Property<string>("ChikuCD")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("HaisouCD")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("ItemCD")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ItemNM")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("JuchuuDenpyouNO")
                        .HasColumnType("int");

                    b.Property<string>("JuchuuKBN")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("JuchuuKyotenCD")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("JuchuuKyotenNM")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("JuchuuSuu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JuchuuYMD")
                        .HasColumnType("date");

                    b.Property<string>("NisugataCD")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("NouSCD")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("NouSSNM")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("Nouki")
                        .HasColumnType("date");

                    b.Property<string>("ShukkaBashoCD")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("ShukkaKyotenCD")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("TankaUnitCD")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Tekiyou1")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UriKeitaiKBN")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UserHinban")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UserHinmei")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("JuchuuNO");

                    b.HasIndex("JuchuuKyotenCD")
                        .HasDatabaseName("IX_Juchuu_KyotenCD");

                    b.HasIndex("NouSCD")
                        .HasDatabaseName("IX_NouSCD");

                    b.HasIndex("NouSSNM")
                        .HasDatabaseName("IX_NouSSNM");

                    b.ToTable("T0000RR_Juchuu_RCS", (string)null);
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.entities.VI_Product", b =>
                {
                    b.Property<string>("NOUSCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserHinban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserHinmei")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VI_PRODUCT", (string)null);
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.entities.VI_SeinouMst", b =>
                {
                    b.Property<string>("NOUSCD")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOUSCD");

                    b.Property<string>("PRODUCT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRODUCT");

                    b.Property<decimal?>("T100A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T100B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T10A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T10B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T110A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T110B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T120A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T120B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T130A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T130B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T140A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T140B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T150A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T150B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T160A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T160B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T20A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T20B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T30A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T30B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T40A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T40B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T50A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T50B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T60A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T60B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T70A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T70B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T80A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T80B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T90A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("T90B")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("VI_SEINOUMST", (string)null);
                });

            modelBuilder.Entity("IMIP.Tochu.Domain.entities.VI_SeinouMstSE", b =>
                {
                    b.Property<string>("NOUSCD")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOUSCD");

                    b.Property<string>("PRODUCT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRODUCT");

                    b.Property<string>("T100A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T10A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T110A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T120A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T130A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T140A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T150A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T160A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T20A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T30A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T40A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T50A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T60A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T70A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T80A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T90A")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VI_SEINOUMSTSE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
