IF OBJECT_ID('VI_SEINOUMSTSE', 'V') IS NULL
BEGIN
    EXEC('
        CREATE VIEW VI_SEINOUMSTSE AS
        SELECT
            PRODUCT,
            NOUSCD,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 10 THEN MIN END)) AS T10A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 20 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 20 THEN MAX END)) AS T20A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 30 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 30 THEN MAX END)) AS T30A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 40 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 40 THEN MAX END)) AS T40A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 50 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 50 THEN MAX END)) AS T50A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 60 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 60 THEN MAX END)) AS T60A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 70 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 70 THEN MAX END)) AS T70A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 80 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 80 THEN MAX END)) AS T80A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 90 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 90 THEN MAX END)) AS T90A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 100 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 100 THEN MAX END)) AS T100A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 110 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 110 THEN MAX END)) AS T110A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 120 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 120 THEN MAX END)) AS T120A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 130 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 130 THEN MAX END)) AS T130A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 140 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 140 THEN MAX END)) AS T140A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 150 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 150 THEN MAX END)) AS T150A,
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 160 THEN MIN END)) + ''～'' +
            CONVERT(VARCHAR, MAX(CASE WHEN NUM = 160 THEN MAX END)) AS T160A
        FROM SI_SEINOUMST
        GROUP BY
            PRODUCT,
            NOUSCD
    ')
END